name: Test and Coverage

on:
  pull_request:
  push:
    branches:
      - main  # Adjust the branch name based on your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: mkdir coverage/tmp && npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.FS_TOKEN }}
